name = "proxy-worker"
main = "functions/proxy-worker.js"
pages_build_output_dir = "./dist"
compatibility_date = "2025-11-13"
workers_dev = true

[[kv_namespaces]]
binding = "PROXY_LOGS"
id = "proxy-db"

[[analytics_engine_datasets]]
binding = "PROXY_LOGS"
dataset = "proxy_events"

[[routes]]
pattern = "proxy-worker.bitsonline.nl/*"
zone_name = "bitsonline.nl"
