name = "proxy-worker"
main = "./proxy-worker/index.js"
compatibility_date = "2025-11-13"

[[kv_namespaces]]
binding = "PROXY_LOGS_KV"
id = "proxy-db"

[[analytics_engine_datasets]]
binding = "PROXY_LOGS_ANALYTICS"
dataset = "proxy_events"

[assets]
directory = "./worker/"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "proxy-worker.bitsonline.nl/*"
zone_name = "bitsonline.nl"




