name = "proxy-worker"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "PROXY_LOGS_KV"
id = "proxy-db"

[[analytics_engine_datasets]]
binding = "PROXY_LOGS_ANALYTICS"
dataset = "proxy_events"

[ai]
binding = "proxy-ai" # available in your Worker code on `env.AI`


