name = "proxy-worker"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "PROXY_LOGS_KV"
id = "proxy-db"

[[analytics_engine_datasets]]
binding = "PROXY_LOGS_ANALYTICS"
dataset = "proxy_events"

[assets]
directory = "/worker"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "*/*"
zone_name = "*"






